name: Terraform Deployment Workflow

 

on:
  workflow_run:
    workflows: ["Terraform Create Resource", "Terraform destroy Resource"]
    types: [requested]
    branches:
      - 'main'

 

jobs:
  manual-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Create Resources Workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.AS5_GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
              workflow: 'Terraform Create Resource',
              ref: 'main'
            });
      - name: Trigger Destroy Resources Workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.AS5_GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
              workflow: 'Terraform destroy Resource',
              ref: 'main'
            });
