name: Terraform destroy Resource

on:
  workflow_call:
    inputs:
      username:
        description: ' a username passed from the caller workflow '
        required: true
        type: string
         
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve

      - name: cleanup terraform state
        run: |
          aws s3 rm s3://s3-terraform-statefile-as5/terraform.tfstate

