name: Deploy-vm

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select description action
        options:
        - apply
        - destroy
        required: true
  
  push:
    branches:
      - main
    
      
jobs:
  create-resources:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Store terraform state
        run: |
          terraform state pull > terraform.tfstate
          aws s3 cp terraform.tfstate s3://s3-terraform-statefile-as5/

  terraform-destroy:
    if: ${{ github.event.inputs.terraform_action == 'destroy' }}
    uses: kalyannkotni/assignment-5.2/.github/workflows/terraform-destroy.yml@main
    with:
      username: kalyannkotni
